### ISSUE TITLE
no graphql module

### ISSUE THREAD

**Issue by thorizer** [atulmy/fullstack-javascript-architecture#14]
In the backend, I see mutation and queries but no express-graphql or graphql in the package.json.  
How are we using grahql in this project exactly  ?

**Comment by atulmy** [comment]
GraphQL is not used in this project. Instead, a hybrid of REST and GraphQL is implemented check [wispy](https://github.com/atulmy/wispy), which is nothing but exposing bunch of JavaScript functions as queries or mutations instead of creating multiple endpoints (REST) or deal with schemas of GraphQL. 

I've been using this implementation in many projects in production and it works seamlessly.

**Comment by thorizer** [comment]
interesting , I loved the structure but can you link me any well structured project that uses node.js + graphql + mongodb ?

**Comment by atulmy** [comment]
Sure, have a loot at HireSmart's codebase at this version: https://github.com/atulmy/hire-smart/tree/f092eae08f23641a6dcc13847b98eed248b9cdf8

The project was later moved away from GraphQL to use Wispy's structure.

**Comment by thorizer** [comment]
@atulmy  I'm thinking of switching from express-graphql to appolo server. Do you think I can switch without heavy editing while keeping the same structure ?
